site_name: NutriPlanner

repo_name: "2023.2-NutriPlanner"
repo_url: "https://github.com/mdsreq-fga-unb/2023.2-NutriPlanner"

theme:
  name: material
  language: "pt"
  icon:
    logo: material/food-variant
    repo: fontawesome/brands/github
  palette:
    primary: "blue"
    accent: "blue"
  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - stylesheets/styles.css

nav:
  - Início: index.md
  - Visão geral do Produto: visao_geral_produto/visao_produto.md
  - Visão do Projeto: visao_projeto/visao_do_projeto.md
  - Desenvolvimento do Software:
    - Processo de Desenvolvimento: processo_desenvolvimento/processo.md
  - Requisitos de Software :
    - Lições Aprendidas:
      - Unidade 1: licoes_aprendidas/licoes_01.md
  - Material + Vídeos:
    - Refências: referencias/referencias.md
    - Vídeos: videos/videos.md