site_name: NutriPlanner

repo_name: "2023.2-NutriPlanner"
repo_url: "https://github.com/mdsreq-fga-unb/2023.2-NutriPlanner"

theme:
  name: material
  language: "pt"
  favicon: docs_separados/assets/logo.png  
  icon:
    logo: material/food-variant
    repo: fontawesome/brands/github
  palette:
    primary: "blue"
    accent: "blue"
  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - stylesheets/styles.css

nav:
  - Início: index.md
  - Visão do Produto e projeto:
    - Visão do produto: visao_geral_produto/visao_produto.md
    - Visão do Projeto: visao_projeto/visao_do_projeto.md
    - Processo de Desenvolvimento: processo_desenvolvimento/processo.md
  - Entrega do Produto: 
    - Proposta de MVP: produto/mvp/prop_mvp.md
    - Backlog SAFe: produto/backlog/backlog_safe.md
  - Entregas das unidades:
    - Unidade 1:
      - História da Facção: docs_separados/historia.md
      - Lições Aprendidas: licoes_aprendidas/licoes_01.md
      - Visão do Produto: visao_geral_produto/slide_01.md
      - Visão do Processo: visao_geral_produto/slide_02.md
    - Unidade 2:
      - Lições Aprendidas: licoes_aprendidas/licoes_02.md
      - Apresentação backlog: visao_projeto/slide_01.md
      - VeriVal -> Equipe "Tanás": docs_separados/verival_tanas.md
    - Refências: referencias/referencias.md
    - Vídeos: videos/videos.md
  - Reuniões: 
    - Reuniões Gerais da Equipe:
      - Ata 1 (05/10/2023):
      - Ata 2 (07/10/2023):
      - Ata 3 (08/10/2023):
      - Ata 4 (12/10/2023):
      - Ata 5 (16/10/2023):
      - Ata 6 (17/10/2023):
      - Ata 7 (08/11/2023):
    - Alinhamentos com Cliente:
      - Relatório de Considerações (08/10/2023): relatorios_consideracoes_cliente/relatorio-08-10-2023.md
      - Relatório de Considerações (09/11/2023): relatorios_consideracoes_cliente/relatorio-09-11-2023.md

